### ISSUE TITLE
[style] избыточные комментарии

### ISSUE THREAD

**Issue by andrei-kuznetsov** [mirragato/GPS#1]
`
DBHelper dbHelper;//Создание БД
`

https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/LocationService.java#L39

База данных создается не здесь. У Роберта Мартина есть хорошая книжка, которая называется "Clean Code: A Handbook of Agile Software Craftsmanship". Прочитайте/просмотрите раздел про комментарии (легко найти pdf версию). Будете приятно удивлены тем, что такие гуру как "дядя Боб" рекомендуют не добавлять комментарии без острой необходимости. Особенно, если комментарии вводят в заблуждение.

Это общая рекомендация к коду, не только к одной конкретной строчке.

**Comment by mirragato** [comment]
Done
