### ISSUE TITLE
[style] использование устаревших API и другие ошибки

### ISSUE THREAD

**Issue by andrei-kuznetsov** [mirragato/GPS#11]
В коде периодически используются устаревшие API. Например, 
https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/Setting.java#L91
или
https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/LocationService.java#L53

Эти и другие проблемы в коде могут быть обнаружены с помощью code analyzer:
https://developer.android.com/studio/write/lint.html#manuallyRunInspections

На текущий момент имеется 9 ошибок и 162 предупреждения:
![image](https://user-images.githubusercontent.com/6942969/33519795-04843b52-d7bf-11e7-8036-fdc7071cfca9.png)

Проанализируйте эти сообщения. Наиболее интересные опишите в пояснительной записке к работе. Обязательно добавьте в раздел "тестирование" результаты анализатора (после исправлений). Кратко опишите наиболее интересные/спорные из неисправленных сообщений, цель: читатель должен понять, что не все замечания были исправлены, и это было осознанное решение.

**Comment by mirragato** [comment]
I incuded a lint and changed errors and warnings. There remained insignificant proposals. But I have problem with `createDialog`, I don't quite undestend his new implementation, cuz on diffrent sites is an old...

**Comment by andrei-kuznetsov** [comment]
Посмотрите документацию на сайте гугла: https://developer.android.com/guide/topics/ui/dialogs.html
