### ISSUE TITLE
[style] конвенции именования сущностей в Java

### ISSUE THREAD

**Issue by andrei-kuznetsov** [mirragato/GPS#12]
Правила именования сущностей в Java описаны в спецификации языка (https://docs.oracle.com/javase/specs/jls/se8/html/jls-6.html#jls-6.1). Без острой необходимости от этих рекомендаций лучше не отходить. Например, имена локальных переменных должны начинаться с маленькой буквы, чтобы их было проще отличать от типов:

https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/Setting.java#L131

Также имена пакетов должны быть осмысленными, уникальными и придерживаться рекомендованной схемы:
https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/Setting.java#L1

Например, name.revkina.gps, или ru.spbstu.kspt.revkina.gps

**Comment by mirragato** [comment]
I created packet with name "kspt.revkina.gps"
