### ISSUE TITLE
[style] дублирование констант

### ISSUE THREAD

**Issue by andrei-kuznetsov** [mirragato/GPS#13]
Эти константы имеют одинаковый смысл, или совпали случайно:

https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/Setting.java#L43-L51

https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/MapsActivity.java#L59-L67

Если одинаковый - то необходимо убрать дублирующееся определение.

**Comment by mirragato** [comment]
Do I need to create a class for constants?

**Comment by mirragato** [comment]
Aded preferenceactivity
