### ISSUE TITLE
[bug] приложение содержит hard-coded значения элементов UI

### ISSUE THREAD

**Issue by andrei-kuznetsov** [mirragato/GPS#15]
https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/MapsActivity.java#L370

Все элементы пользовательского интерфейса (за редким исключением) должны быть вынесены в ресурсы. Для стандартных надписей (типа OK, отмена, применить, и т.п.) в ресурсах андроида уже есть подходящие элементы. Например: `android.R.string.ok` или `android.R.string.cancel`

**Comment by mirragato** [comment]
Done
