### ISSUE TITLE
[design] хранение времени и даты в SQLite 

### ISSUE THREAD

**Issue by andrei-kuznetsov** [mirragato/GPS#17]
SQLite не поддерживает тип timestapm, однако в большинстве случаев, это не нужно. Традиционно время может быть измерено в секундах или миллисекундах (например, см. https://docs.oracle.com/javase/7/docs/api/java/lang/System.html#currentTimeMillis())

Для хранения даты рекомендуется использовать один числовой тип: https://sqlite.org/datatype3.html#date_and_time_datatype

Вместо двух строк:
https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/DBHelper.java#L85-L86

**Comment by mirragato** [comment]
2 line were merged
