### ISSUE TITLE
[bug] Время местоположения может сохраняться неправильно

### ISSUE THREAD

**Issue by andrei-kuznetsov** [mirragato/GPS#19]
https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/DBHelper.java#L76-L78

Представим, что первая инструкция выполнилась 2017-12-03 в 23:59:59.999 => DATE_KONTROL=2017-12-03, а вторая 2017-12-04 в 00:00:00.001 => TIME_KONTROL = 00:00:00. Записанное время отличается на сутки (!) от ожидаемого времени. Кроме того, ни одно из приведенных выше значений не соответствует времени координаты.

Необходимо сохранять оригинальное время location объекта, которое может быть вычислено как `location.getTime()`:
https://github.com/mirragato/GPS/blob/85edbd04a23e0df7ac32ff958af96e00e2868464/app/src/main/java/gps/com/gps/LocationService.java#L99-L100

**Comment by mirragato** [comment]
I changed the functon `createNewTable`
